USE [master]
GO

/****** Object:  Database [SistemaMLP]    Script Date: 9/4/2022 10:32:14 p. m. ******/
CREATE DATABASE [SistemaMLP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SistemaMLP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SistemaMLP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SistemaMLP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SistemaMLP_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SistemaMLP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SistemaMLP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SistemaMLP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SistemaMLP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SistemaMLP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SistemaMLP] SET ARITHABORT OFF 
GO

ALTER DATABASE [SistemaMLP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SistemaMLP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SistemaMLP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SistemaMLP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SistemaMLP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SistemaMLP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SistemaMLP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SistemaMLP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SistemaMLP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SistemaMLP] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SistemaMLP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SistemaMLP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SistemaMLP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SistemaMLP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SistemaMLP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SistemaMLP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SistemaMLP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SistemaMLP] SET RECOVERY FULL 
GO

ALTER DATABASE [SistemaMLP] SET  MULTI_USER 
GO

ALTER DATABASE [SistemaMLP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SistemaMLP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SistemaMLP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SistemaMLP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SistemaMLP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SistemaMLP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SistemaMLP] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SistemaMLP] SET  READ_WRITE 
GO

